### PR TITLE
Fix TypeScript checking and include it in CI

### PR DESCRIPTION
**Pull request by silvenon**
- chore: fix clashing types in TypeScript
- chore: simplify TypeScript configuration
- ci: start type checking with TypeScript
<br/><br/><br/><url>LiveURL: https://orbit-test-typescript.surge.sh</url>

### CODE REVIEW

**Comment by silvenon** [comment]
Make sure to rebase, not squash, if you're merging.

**Comment by silvenon** [comment]
Damnit, for some reason `.yarnclean` doesn't automatically trigger Yarn, I had to run `yarn autoclean --force` the first time, then it started doing it on its own.

**Comment by silvenon** [comment]
I figured it out! 🚀 I needed to add `.yarnclean` to hash files because CI should rebuild dependencies when contents of `.yarnclean` change. CI was failing simply because `yarn install` didn't run, so `@types/react-native` was still there.

**Review by mainframev — APPROVED** [review]

**Comment by silvenon** [comment]
Just rebased to fix conflicts.

**Pull request merged**
