### PR TITLE
chore: eslint jest rules

### LINKED ISSUE #2348: Prohibit use of .only() in Jest tests via ESLint
`eslint-plugin-jest` has the rule to prohibit the use of `.only()`, we should use it. It would probably be best to do this after #2347, but it's fine either way.

### PR DESCRIPTION
**Pull request by mainframev**
- forbid usage of [focused-tests](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-focused-tests.md)
- consistent `it` [consistent-test-it](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/consistent-test-it.md)
- removed identical titles [no-identicial-title](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/no-identical-title.md)

Fixes #2348.

and etc. <br/><br/><br/><url>LiveURL: https://orbit-chore-eslint-jest-only.surge.sh</url>

### CODE REVIEW

**Review by silvenon — COMMENTED** [review]
I agree with most of these rules, but I would like to discuss `jest/consistent-test-it`. I like the freedom of sometimes using `it` and sometimes `test` because `it` tests can be read like "it uses media queries", where `test` tests can be read like "test accessibility" and "test styles". I don't think enforcing either one brings value, I like combining them.

**Comment by mainframev** [comment]
@silvenon i think it's better to have consistency and left only `it`, description of `it` can be written as you want :)

**Comment by vepor** [comment]
I don't have any strong opinion for `consistent-test-it`, I don't see any major problem with having both. It doesn't mean that it will be harder to read tests if we use both – the syntax is the same.

**Comment by mainframev** [comment]
`it` should fit better with `@testing-library` since `it` focused on output, like: `it("should render ...")`

they are the same, just naming differences

**Review by silvenon — APPROVED** [review]
Ok, I'm fine with either 👍 please resolve conflicts.

**Pull request merged**
