### PR TITLE
fix(tokens): fix bundle tokens definitons

### PR DESCRIPTION
**Pull request by mainframev**
[Slack request.](https://skypicker.slack.com/archives/C7T7QG7M5/p1690814179553659) Some typos during the definition of button deprecated tokens.

### CODE REVIEW

**Review by DSil — COMMENTED** [review]
LGTM. Pipeline is failing because it is missing the class definition for the new palette colors on `backgroundColor` and `color` under `common/tailwind` files. This ensures we always support all colors for the palette tokens we have defined 🙂

**Comment by mainframev** [comment]
> LGTM. Pipeline is failing because it is missing the class definition for the new palette colors on `backgroundColor` and `color` under `common/tailwind` files. This ensures we always support all colors for the palette tokens we have defined 🙂
> 
> Building the components package will also update the types for Box and Separator props, as they accept all palette colors

Yeah, already fixing this 💪🏻

**Review by DSil — COMMENTED** [review]
Shouldn't Box and Separator types be updated on this PR as well?

I also feel the second commit message should not be a fix, as I don't think it's something worth mentioning on the changelog (the first commit already covers the fix, imo)

**Comment by mainframev** [comment]
> Shouldn't Box and Separator types be updated on this PR as well?
> 
> I also feel the second commit message should not be a fix, as I don't think it's something worth mentioning on the changelog (the first commit already covers the fix, imo)

I will still squash it

**Pull request merged**
