### PR TITLE
improve(Commitlint): add the improve type to commitlint

### PR DESCRIPTION
**Pull request by aalises**
Adds the `improve` type to the commitlint configuration, so now you can do commits with the `improve` type. This is useful for huge tooling and platform changes, like the commit of this MR of course 😂

e.g. of usage (also in the commit)

```
improve(Something): adds a lot of awesome changes
```

### CODE REVIEW

**Comment by mainframev** [comment]
I would stick with standard conventional commits type, i think it's better to specify custom scope for it, not commit type

**Comment by silvenon** [comment]
@mainframev I suggested this in #2330.

**Comment by vepor** [comment]
As suggested in the #2305 I don't think that we have stick to standard conventional commits type.

**Comment by aalises** [comment]
@mainframev I am fine with whatever! I think in that case it might be okay cc @vepor

**Review by silvenon — APPROVED** [review]
Ok, Victor and I synced on this. 😃 Thank you so much, I can't wait to use `improve`! ❤️❤️❤️

**Review by vepor — APPROVED** [review]

**Pull request merged**
