### PR TITLE
docs: typography font typo

### PR DESCRIPTION
**Pull request by hajnyon**
Fix of a typo in typography docs.

### CODE REVIEW

**Comment by DSil** [comment]
@hajnyon thank you for your contribution. Can you please reword the commit so that the scope is `docs:...` and not `fix(docs):...`?

**Review by DSil — APPROVED** [review]
Thanks again!

**Comment by hajnyon** [comment]
> @hajnyon thank you for your contribution. Can you please reword the commit so that the scope is `docs:...` and not `fix(docs):...`?

Hey, I didn't amend the commit, is it ok to just rename the PR?

**Comment by DSil** [comment]
> > @hajnyon thank you for your contribution. Can you please reword the commit so that the scope is `docs:...` and not `fix(docs):...`?
> 
> Hey, I didn't amend the commit, is it ok to just rename the PR?

Oh 🤦‍♂️ my bad. No, please reword the commit

**Pull request merged**
